name: cypress parallel
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Cypress
        uses: cypress-io/github-action@v5
        with:
          runTests: false

  tests:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Test Parallel
        uses: cypress-io/github-action@v5
        with:
          spec: cypress/tests/test-suites/ui-tests/simple-tests/simple-test-${{matrix.containers}}.cy.js
          browser: chrome

      - name: Save test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results-${{ matrix.containers }}
          path: build/allure-results
          retention-days: 1

  report:
    runs-on: ubuntu-latest
    needs: tests
    if: always()
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: allure-results-download

      - name: Prepare merged results
        run: |
          mkdir -p build/allure-results
          cp -r allure-results-download/*/* build/allure-results/

      - name: Load test report history
        uses: actions/checkout@v3
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true